apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pokedex
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pokedex-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - name: pokedex
          image: kajetanp/pokedex:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:  
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-service
  labels:
    app: pokedex-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: pokedex-app
